include/boost/fiber/detail/config.hpp
Since the usage of variadic templates is now enabled by default and not emulated, the definition of the `BOOST_FIBERS_USE_VARIADIC_FIBER` macro can be removed.
=> Remove definition of BOOST_FIBERS_USE_VARIADIC_FIBER

doc/queue.qbk
The descriptions of [un]bounded_channel::push() and the other push variants
are very similar, and must be kept consistent. Similarly, all the pop variants
must be kept consistent. Use QuickBook templates to supply much of the wording
for these methods.
=> Fix "enchanneled"/"dechanneled". Encapsulate some redundant wording.

doc/fiber.qbk, doc/mutexes.qbk, doc/rational.qbk
The clause "if the mutex is not recursive" appeared in member descriptions for mutexes known not to be recursive.
=> Tweaks to new documentation

examples/priority.cpp
The example no longer compiles without this override.
=> Add ready_fibers() override for examples/priority.cpp.

doc/channel.qbk, test/test_bounded_channel.cpp
I realize channel::is_closed() is likely to vanish soon, but until it does, we should describe its effects properly to avoid confusion.
test_try_push() should call try_push() rather than push().
=> test_try_push() fix and channel::is_closed() wording

examples/priority.cpp, include/boost/fiber/properties.hpp
It's more straightforward to use the underlying type: fiber_context*.
=> Eliminate opaque fiber_properties::back_ptr typedef.

doc/channel.qbk, test/test_bounded_channel.cpp
We intend to document that bounded_channel(hwm) is equivalent to
bounded_channel(hwm, (hwm-1)). That may or may not simplify the code, but it
certainly simplifies the reader's mental model of the relationship between the
two constructors.
However, that assertion requires that for bounded_channel(hwm), lower_bound()
in fact return (hwm-1). Test for that.
Also use BOOST_CHECK_EQUAL(a, b) instead of BOOST_CHECK(a == b) where
applicable, since the former is more informative when the test fails.
Sadly, tests on channel_op_status must still use BOOST_CHECK(a == b) --
apparently because channel_op_status, as an enum class, cannot be streamed to
std::ostream?
=> Add tests for bounded_channel::lower_bound().

doc/callbacks.qbk, doc/fibers.qbk, examples/adapt_callbacks.cpp, examples/adapt_method_calls.cpp, examples/asio/detail/promise_handler.hpp, examples/asio/detail/yield.hpp, examples/asio/promise_completion_token.hpp, examples/asio/yield.hpp
This covers both generic callbacks (adapt_callbacks.cpp,
adapt_method_calls.cpp) and custom Asio completion tokens (yield.hpp,
promise_completion_token.hpp, detail/yield.hpp, detail/promise_handler.hpp).
Mark up the relevant source files to provide code snippets for callbacks.qbk.
=> Add callbacks.qbk about interfacing Fiber with async callbacks.

doc/customization.qbk, doc/fiber.qbk, examples/priority.cpp, include/boost/fiber/operations.hpp
I changed my advice about setting properties.
I also changed `examples/priority.cpp` to reflect my new understanding, converting the `init()` function to a `launch()` function that launches the fiber and immediately sets its properties.
Scrutinizing `priority.cpp` output, I discovered a bug in my `priority_scheduler::property_change()` method. Given a ready queue containing [medium(2), low(1), high(0)], a `property_change()` call with `high` reset to priority 3 would move it here: [medium(2), high(3), low(1)].
That rubbed my nose in the fact that my "clever" single-pass `property_change()` logic was hard to reason about -- bad news for an example program! I decided to convert it to two simpler passes: the first to find and unlink the passed fiber_context\*, the second to re-insert it in …
=> Correct mistaken advice about properties for newly-launched fiber.

examples/Jamfile.v2, examples/asio/autoecho.cpp
This example program is intended to exercise both ends of several client / server connections on multiple threads, and terminate gracefully when done. It illustrates:
* multiple threads calling run() on the same asio::io_service instance
* shutdown by calling io_service::stop() when the last client finishes
* interrupting the listening server fiber.
Warning: we may need to interrupt the server fiber _before_ calling io_service::stop().
=> Add examples/asio/autoecho.cpp to drive echo client/server automatically.

doc/callbacks.qbk, examples/asio/autoecho.cpp, examples/asio/detail/yield.hpp, examples/asio/yield.hpp
Given the necessity for fibers::asio::round_robin to share its ready queue
among all threads calling io_service::run() on the same io_service instance,
the capability to allow hop (or not) in the fibers::asio::yield mechanism is
redundant.
I shouldn't have put this on top of the autoecho change, but I don't know git well enough to untangle them.
=> Remove 'yield_hop' and the whole allow_hop_ mechanism.

examples/asio/round_robin.hpp
This gives notify() something to cancel if need be. It has bothered me that if the dispatcher calls sched_algorithm::suspend_until( time_point::max()), and therefore suspend_timer_ is not set and no async_wait() call is outstanding, notify() cannot have any effect.
I very much doubt steady_timer::expires_at() is implemented using std::condition_variable::wait_until(), so I don't believe we should have a problem calling expires_at() with time_point::max().
Truthfully, with the lambda loop, I'm not sure under what circumstances the dispatcher will *ever* call suspend_until(), though.
Avoid resetting the timer to the same abs_time. Since setting an asio timer cancels any outstanding async_wait() call -- apparently even if the new abs_time is the same as the previous -- I am concerned about …
=> Make round_robin::suspend_until() always set asio timer.

doc/fiber.qbk, doc/scheduling.qbk
This documentation pass is incomplete: given that, on this branch, the work-sharing and work-stealing schedulers have migrated from the examples directory into the core library, the documentation passages describing the work-sharing scheduler should be removed. Not yet done.
=> Fix documentation about random_chase_lev et al.

include/boost/fiber/future/async.hpp
I'm using a custom valgrind-aware allocator for creating fiber so that
the valgrind log is clean.
It worked well with fiber::fiber() but wasn't used in fiber::async(). 
Unless there are reasons unknown to me, I believe this to be an oversight, and this
commit fixes it.
=> Fix allocator-aware fiber::async() overload allocator forwarding.

include/boost/fiber/detail/cpu_relax.hpp
Hello,
I'm trying to build the boost 1.63 library with the Intel 17.0 compiler (latest update) in the vs2015 environment. Several targets fail to build because the definition of the cpu_relax macro isn't correct.
This change corrects the problem and allows the build to complete successfully.  Is this the right way to correct the problem? At Intel, we like to set up the Intel compiler so the macro symbols emulate our "host" compiler, cl.exe on Windows and gcc on Linux. This way whatever work folks put into making boost (or some other project) work for cl.exe should also work for the Intel compiler (or it would be a compiler bug that should be fixed)
Without this change I get a message like this:
./boost/fiber/detail/spinlock_ttas.hpp(66): error: invalid constant in assembly language …
=> fix cpu_relax.h for compilation with Intel compiler on Windows

include/boost/fiber/future/detail/task_object.hpp
Hallo Oliver,
with msvc 19.10 and compiler option /std:c++latest activated, the code path using std::apply is engaged and triggers a typo 😄 
Signed-off-by: Daniela Engert <dani@ngrt.de>
=> unbalanced opening parenthesis

include/boost/fiber/detail/wrap.hpp, include/boost/fiber/future/detail/shared_state.hpp
GCC before v5 has issues invoking copy constructors using braces:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51747
=> Work around compiler limitations in g++-4.9

include/boost/fiber/detail/convert.hpp, include/boost/fiber/future/detail/task_object.hpp, include/boost/fiber/future/packaged_task.hpp, include/boost/fiber/future/promise.hpp
The place to use the conversion from a potentially-fancy pointer to a raw pointer is also with construct() since that requires raw pointers.
=> Construct using the raw pointer and use pointer_traits.to_address

include/boost/fiber/detail/futex.hpp
to fix cross-compilation error with MinGW and Posix threads.
=> Changed #include "Windows.h" to "windows.h" to fix cross-compilation

src/numa/linux/topology.cpp
Therefore replace inheritance by lifting std::iterator's members into the derived class.
Signed-off-by: Daniela Engert <dani@ngrt.de>
=> Inheriting std::iterator is deprecated in C++17

include/boost/fiber/future/detail/shared_state_object.hpp, include/boost/fiber/future/detail/task_object.hpp, test/test_async_dispatch.cpp
And so is std::allocator<void>. Replace them by their cousins from std::allocator_traits. In addition to that, use std:allocator_traits wherever possible. Without that, heaps of deprecation warnings will fall onto humble users when compiling with MSVC 15 in C++17 mode.
Signed-off-by: Daniela Engert <dani@ngrt.de>
=> Most members of std::allocate are deprecated in C++17

src/numa/freebsd/pin_thread.cpp
`pthread_t` is opaque and cannot be used with `CPU_WHICH_TID`. Looking at Linux implementation `pthread_setaffinity_np()` should work on FreeBSD as well.
CC @juikim
```diff
--- src/numa/linux/pin_thread.cpp
+++ src/numa/freebsd/pin_thread.cpp
@@ -8,7 +8,7 @@
extern "C" {
#include <pthread.h>
-#include <sched.h>
+#include <pthread_np.h>
}
#include <system_error>
@@ -28,7 +28,7 @@ void pin_thread( std::uint32_t cpuid) {
BOOST_FIBERS_DECL
void pin_thread( std::uint32_t cpuid, std::thread::native_handle_type h) {
-    cpu_set_t set;
+    cpuset_t set;
CPU_ZERO( & set);
CPU_SET( cpuid, & set);
int err = 0;
```
=> Unbreak build on FreeBSD after 7ff5a3564b0f

examples/asio/detail/yield.hpp
The previous hook required the Fn to be CopyConstructible, wheras ASIO 1.66+ permits MoveConstructible-only CompletionHandlers.
Resolves: https://github.com/boostorg/beast/issues/1134
=> Fix asio_handler_invoke hook in ASIO example

include/boost/fiber/context.hpp
This fixes the following warning:
```
/remote/intdeliv/components/osp/Boost/18-0-0-6/include/boost/fiber/context.hpp:422:36: error: unused parameter 'c' [-Werror,-Wunused-parameter]
run_( boost::context::fiber && c) {
^
1 error generated.
```
=> Ignore unused argument warning with clang.

src/scheduler.cpp
during the wake path caused by a local thread holding the lock for too long
=> Fix high contention on remote_ready_splk_ 

include/boost/fiber/detail/cpu_relax.hpp
PAUSE was introduced in MIPS32r2.
Example of build failure: https://downloads.openwrt.org/snapshots/faillogs/mips_mips32/packages/boost/compile.txt
Ctrl+F error: will show
```
{standard input}:1942: Error: opcode not supported on this processor: mips32 (mips32) `pause'
{standard input}:2017: Error: opcode not supported on this processor: mips32 (mips32) `pause'
```
=> cpu_relax: Don't use pause for MIPS under rev 2

include/boost/fiber/detail/cpu_relax.hpp
BOOST_ARCH_MIPS as a macro is totally broken. It always gets defined to either 32
or 64 with a bunch of zeroes depending on the architecture.
Use GCC's internal define to check the architecture properly.
=> cpu_relax: Fix MIPS check

include/boost/fiber/buffered_channel.hpp, include/boost/fiber/unbuffered_channel.hpp
Found with clang-tidy's cert-dcl21-cpp
=> treewide: Fix operator++/operator-- const

src/properties.cpp
Found with clang-tidy's cppcoreguidelines-pro-type-static-cast-downcast
=> properties: Use dynamic_cast for derived classes

include/boost/fiber/context.hpp, include/boost/fiber/future/future.hpp
Found with modernize-pass-by-value
=> treewide: Use std::move where appropriate

include/boost/fiber/buffered_channel.hpp, include/boost/fiber/unbuffered_channel.hpp, src/condition_variable.cpp, src/context.cpp, src/recursive_timed_mutex.cpp, src/timed_mutex.cpp
Found with clang-tidy's modernize-use-auto
=> treewide: Use auto where appropriate

include/boost/fiber/buffered_channel.hpp, include/boost/fiber/context.hpp, include/boost/fiber/detail/thread_barrier.hpp, include/boost/fiber/unbuffered_channel.hpp, src/barrier.cpp, src/condition_variable.cpp, src/mutex.cpp, src/recursive_mutex.cpp, src/recursive_timed_mutex.cpp, src/timed_mutex.cpp
Found with clang-tidy's readability-else-after-return
=> treewide: Do not use else after return or throw

include/boost/fiber/algo/algorithm.hpp, include/boost/fiber/algo/round_robin.hpp, include/boost/fiber/algo/shared_work.hpp, include/boost/fiber/algo/work_stealing.hpp, include/boost/fiber/exceptions.hpp, include/boost/fiber/fss.hpp, src/future.cpp
Found with clang-tidy's cppcoreguidelines-explicit-virtual-functions
=> future: Use override instead of virtual

include/boost/fiber/exceptions.hpp, include/boost/fiber/fiber.hpp, include/boost/fiber/properties.hpp
Found with clang-tidy's google-explicit-constructor
=> treewide: Add explicit to single argument constructors

include/boost/fiber/algo/algorithm.hpp, include/boost/fiber/context.hpp, include/boost/fiber/unbuffered_channel.hpp
Found with modernize-use-equals-default
=> treewide: Replace {} with = equals

include/boost/fiber/future/async.hpp
- std::result_of has been deprecated in C++17 and will be removed in C++20.
- It has been removed by latest MSVC standard library with C++20 enabled. The package can't be compiled when flag `/std:c++latest` is set.
https://github.com/boostorg/asio/commit/69a6480fc0640288226f71b147a2c7847277a431
=> Fix removed std::result_of for async with MSVC and C++20

build/Jamfile.v2, test/Jamfile.v2
PR related to issue https://github.com/boostorg/fiber/issues/252.
Flag -fsplit-stack is only available on Linux according error message and documentation.
=> Split stack flag

build/Jamfile.v2, include/boost/fiber/buffered_channel.hpp, include/boost/fiber/condition_variable.hpp, include/boost/fiber/context.hpp, include/boost/fiber/mutex.hpp, include/boost/fiber/operations.hpp, include/boost/fiber/recursive_mutex.hpp, include/boost/fiber/recursive_timed_mutex.hpp, include/boost/fiber/scheduler.hpp, include/boost/fiber/timed_mutex.hpp, include/boost/fiber/unbuffered_channel.hpp, include/boost/fiber/waker.hpp, src/condition_variable.cpp, src/context.cpp, src/mutex.cpp, src/recursive_mutex.cpp, src/recursive_timed_mutex.cpp, src/scheduler.cpp, src/timed_mutex.cpp, src/waker.cpp
introduce waker and wait_queue abstractions. fixes #251, #259
```
* remove context::wait_hook_ and context::twstatus in flavor to waker_epoch_ and waker class
* this avoids data races in case of wait_until() operations, when the context
could be timeouted and rescheduled on the other OS thread. In this case could
be data races with context::wait_hook_ and inconsistences context::twstatus
states.
* using context::waker_epoch_ introduces mechanism when the old wakers become
outdated and waker::wake() is just no op. This fixes data races explained in
the previous point
* fibers waiting queue with timeouts and notification mechanisms are incapsulated into
wait_queue class. This introduce simple abstraction level to be used in
different synchronization primitives
* the same wait_queue is used …
```
=> introduce waker and wait_queue abstractions. fixes #251, #259

include/boost/fiber/unbuffered_channel.hpp, test/test_unbuffered_channel_post.cpp
For discussing the fix I suggested for https://github.com/boostorg/fiber/issues/268.
=> Fix issue #268: Delay creation of waker in unbuffered_channel::push

include/boost/fiber/algo/algorithm.hpp, include/boost/fiber/fiber.hpp, include/boost/fiber/operations.hpp, include/boost/fiber/properties.hpp, src/properties.cpp
- It's unlikely that properties are null, it is null only the very
first time the fiber is scheduled.
- We don't need the dynamic_cast in notify, we can already use the
right type, since it is used only with algorithm_with_properties
anyway.
- Allow user defined properties to specify they don't want to use
dynamic_cast but they prefer static_cast for performance reason
(and then it's their responsibility to ensure the types are ok).
=> Speed up properties a bit

include/boost/fiber/detail/cpu_relax.hpp
The pause MIPS instruction was added in version 2.6 of the standard. Unfortunately,
octeon+ seems to be based on an older standard. Also unfortunately GCC doesn't
have a macro for minor ISA versions.
=> cpu_relax:  exclude octeon+ from the MIPS list

include/boost/fiber/detail/cpu_relax.hpp
It turns out that this is also broken on mips64el. Further testing
reveals that
-mips32r2 -mtune=mips32r2 -mabi=32
compiles the PAUSE instruction just fine whereas
-mips64r2 -mtune=mips64r2 -mabi=64
does not. The PAUSE instruction was introduced in version 2.6 of the
MIPS ISA and GCC for some reason does not allow usage of it with MIPS64.
Modify the macro to fix the situation instead of just matching on
octeon, which is not quite correct.
=> cpu_relax: fixup MIPS check for 64-bit

include/boost/fiber/context.hpp, include/boost/fiber/fiber.hpp, include/boost/fiber/properties.hpp
This PR allows fibers to be constructed with properties set. All existing APIs are kept and there is no ABI change.
It fixes issue https://github.com/boostorg/fiber/issues/283
=> Allow setting fiber properties on construction

include/boost/fiber/detail/futex.hpp
Fix the following build failure on 32-bit architectures using 64-bit
time_t (e.g. riscv32):
| ./boost/fiber/detail/futex.hpp:31:23: error: use of undeclared identifier 'SYS_futex'
|     return ::syscall( SYS_futex, addr, op, x, nullptr, nullptr, 0);
|                       ^
| 1 error generated.
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> futex: fix build on 32-bit architectures using 64-bit time_t

src/numa/linux/topology.cpp
This is detected as an error in C++20 (spaceship) in clang 14, since the operators become ambiguous against reversed candidates.
=> Add missing const on comparison operators

include/boost/fiber/future/async.hpp
it fixes build with C++20, because C++20 removed std::result_of.
=> fix std::result_of for cpp20

src/numa/windows/pin_thread.cpp
It fixes the following error during build using CMake and MinGW-w64:
(it allows to build whole Boost successfully)
```log
[ 27%] Building CXX object libs/fiber/CMakeFiles/boost_fiber_numa.dir/src/numa/windows/pin_thread.cpp.obj
C:\boost\libs\fiber\src\numa\windows\pin_thread.cpp: In function 'void boost::fibers::numa::pin_thread(uint32_t)':
C:\boost\libs\fiber\src\numa\windows\pin_thread.cpp:26:42: error: invalid conversion from 'HANDLE' {aka 'void*'} to 'std::thread::native_handle_type' {aka 'long long unsigned int'} [-fpermissive]
26 |     pin_thread( cpuid, ::GetCurrentThread() );
|                        ~~~~~~~~~~~~~~~~~~^~
|                                          |
|                                          HANDLE {aka void*}
In file included from …
```
=> Fix build with cmake and MinGW

include/boost/fiber/detail/cpu_relax.hpp
@olk Remember we were wondering why `context` was fixed but `fiber` failed? I preprocessed sources and found the cause. Of course this could not possibly work.
=> Unbreak fiber for macOS PPC

include/boost/fiber/buffered_channel.hpp, src/waker.cpp
I also experienced this problem #256 and was able to reproduce the bug with @dixlorenz 's snippet. It seems the @dixlorenz suggestion of yielding inside spinlock_ttas would fix this but the problem is context header is only defined later. Since I don't have a deep understanding of this project I didn't felt comfortable of changing include header files order, also have no clue if that would be possible. 
I managed to fix the @dixlorenz snippet by yielding upfront in every buffered_channel call if spinlock_ttas try_lock fails. Of course this doesn't fix the spinlock_ttas problem but at least it seems to fix the buffered_channel hanging during the spinlock.
=> fix buffered_channel of issue #256 - bug in spinlock_ttas

include/boost/fiber/detail/cpu_relax.hpp
Clang also defines the uppercase ```__POWERPC__``` symbol so the commit
2bd8eb02f81ab8297aa89b8cb29b0f3867b9fafe breaks the build on ELF
PowerPC systems. Since we know this is already a PowerPC system
with ```BOOST_ARCH_PPC``` then check for the vendor ```__APPLE__``` instead.
=> Unbreak fiber for ELF PowerPC building with Clang

include/boost/fiber/future/detail/shared_state.hpp
this is in response to the deprecation warning noted in the mailing list.
I think this patch will get rid of the warning, and also give smaller objects on some compilers. 
see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61458 for details of std::aligned_storage size.
"
[build] /usr/include/boost/fiber/future/detail/shared_state.hpp:160:19:
warning: 'aligned_storage<4, 4>' is deprecated [-Wdeprecated-declarations]
[build]   160 |     typename std::aligned_storage< sizeof( R), alignof(
R) >::type  storage_{};
[build]       |                   ^
[build] /usr/include/boost/fiber/future/promise.hpp:28:22: note: in
instantiation of template class
'boost::fibers::detail::shared_state<int>' requested here
[build]    28 |     typedef typename shared_state< R >::ptr_type   ptr_type;
"
=> avoid deprecated std::aligned_storage

build.jam, build/Jamfile.v2, examples/Jamfile.v2, examples/numa/Jamfile.v2, performance/fiber/Jamfile.v2, performance/fiber/numa/Jamfile.v2, performance/thread/Jamfile.v2, test/Jamfile.v2
This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.
This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:
- https://github.com/boostorg/boost/pull/854
This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.
=> Add support for modular build structure.

include/boost/fiber/stack_allocator_wrapper.hpp
fix #314 , compile error when used as shared library on windows with MSVC.
=> remove BOOST_FIBERS_DECL on function definition

include/boost/fiber/context.hpp, src/context.cpp
Trick from Boost.Stacktrace https://github.com/boostorg/stacktrace/blob/0a1f8ac9a0caf250753411e82c645f750ba99317/include/boost/stacktrace/frame.hpp#L34
Closes #321
=> Implement std::hash for boost::fibers::context::id
